package org.royersfordpack531.popcorn;

public enum Popcorn 
{
    CASH,
    MICROWAVE_BUTTER,
    MICROWAVE_LIGHT,
    CARMEL_WITH_NUTS,
    CHOCOLATE_DRIZZLE,
    WHITE_CHEDDAR,
    KETTLE_CORN,
    JALAPENO_CHEDDAR,
    BUFFALO_CHEDDAR,
    BACON_RANCH,
    CHOCOLATE_CARMEL_CRUNCH,
    CARMEL,
    MILITARY_SILVER,
    MILTARY_GOLD,
    KERNELS  
}
